theme: jekyll-theme-slate
- name: Azure WebApp
  uses: Azure/webapps-deploy@v2
theme: jekyll-theme-minimal
- title: Savage Crypto's homepage
  description: Bookmark this to keep an eye on my project updates!
  
